### ISSUE TITLE
wordpress5.7,PHP8.0.3配置出现致命错误。

### ISSUE THREAD

**Issue by NyaDoo** [sy-records/wordpress-qcloud-cos#14]
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: /etc/ssl/certs (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201 Stack trace: #0 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError() #2 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(201): GuzzleHttp\Handler\CurlFactory::finish() #3 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(130): GuzzleHttp\Handler\CurlMultiHandler->processMessages() #4 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute() #6 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #7 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #8 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #9 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #10 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(67): GuzzleHttp\Promise\Promise->wait() #11 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}() #12 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #13 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(103): GuzzleHttp\Promise\Promise->wait() #15 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #16 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute() #17 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Qcloud/Cos/Client.php(116): GuzzleHttp\Command\ServiceClient->__call() #18 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/wordpress-qcloud-cos.php(100): Qcloud\Cos\Client->__call() #19 /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/wordpress-qcloud-cos.php(569): cos_check_bucket() #20 /www/wwwroot/NyaDoo_Main/wp-includes/class-wp-hook.php(292): cos_setting_page() #21 /www/wwwroot/NyaDoo_Main/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #22 /www/wwwroot/NyaDoo_Main/wp-includes/plugin.php(484): WP_Hook->do_action() #23 /www/wwwroot/NyaDoo_Main/wp-admin/admin.php(259): do_action() #24 /www/wwwroot/NyaDoo_Main/wp-admin/options-general.php(10): require_once('...') #25 {main} thrown in /www/wwwroot/NyaDoo_Main/wp-content/plugins/wordpress-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 201
此站点遇到了致命错误，请查看您站点管理员电子邮箱中收到的邮件来获得指引。

了解有关对WordPress进行故障排除的更多信息。

**Comment by sy-records** [comment]
php配置问题
