### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Promise\Coroutine::of()

### ISSUE THREAD

**Issue by yduke** [sy-records/wordpress-qcloud-cos#15]
重现步骤：
插件在运行中，且已配置好存储桶信息

1、当修改本地文件夹和URL前缀，例如由 wp-content 改成wp-content/uploads
2、点击保存后WordPress报错：

`Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Promise\Coroutine::of() in /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php:362 Stack trace: #0 /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(181): GuzzleHttp\Promise\coroutine() #1 /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php(79): GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}() #2 /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}() #3 /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync() #4 /www/wwwroot/打码 in /www/wwwroot/打码/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php on line 362`

**Comment by sy-records** [comment]
你有安装其他依赖guzzle组件的插件，可以停掉后再试
