### ISSUE TITLE
点保存后报错

### ISSUE THREAD

**Issue by pincman** [sy-records/wordpress-qcloud-cos#17]
atal error: Uncaught Error: Call to undefined method GuzzleHttp\Psr7\Uri::resolve() in /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Serializer.php:161 Stack trace: #0 /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Serializer.php(127): GuzzleHttp\Command\Guzzle\Serializer->createCommandWithUri() #1 /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Serializer.php(59): GuzzleHttp\Command\Guzzle\Serializer->createRequest() #2 /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Qcloud/Cos/Client.php(193): GuzzleHttp\Command\Guzzle\Serializer->__invoke() #3 /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(195): Qcloud\Cos\Client->commandToRequestTransformer() #4 /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud- in /data/wwwroot/jikexingkong/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Serializer.php on line 161

**Comment by sy-records** [comment]
这个是因为有其他使用了guzzle的插件，冲突了。

可以排除下
