### ISSUE TITLE
[Bug] 「不在本地保留备份」 功能不可用

### ISSUE THREAD

**Issue by h0wardch3ng** [sy-records/wordpress-qcloud-cos#18]
「不在本地保留备份」 功能不可用
期望功能步骤：
1.  用户上传图片（图片文件存到 `/wp-content/uploads/{year}/{month}` 目录下）
2. 插件监视目录`/wp-content/uploads/{year}/{month}`有更新，上传到 COS
3. 删除目录`/wp-content/uploads/{year}/{month}`下对应的图片文件（含各类大小的缩略图）
4. 文章内插入的图片 URL 自动更新为 COS 的 URL（https://bucket-appid.cos.ap-xxx.myqcloud.com）

目前 Bug：
勾选「不在本地保留备份」后
1. 图片文件依旧占用目录空间，并没有删除
2. 文章内插入的图片 URL 并没有自动更新为 COS 的 URL

**Comment by sy-records** [comment]
插件仅支持从媒体库上传的图片
