### ISSUE TITLE
上传至媒体库时报错，无法正常使用

### ISSUE THREAD

**Issue by AH-dark** [sy-records/wordpress-qcloud-cos#20]
- PHP版本：8.0.14
- WordPress 版本：5.9.2
- 插件版本：2.0.2

在通过 POST /wp-admin/async-upload.php 上传附件时出现如下错误

在使用 2.0.1 及以前版本插件时并未出现此类错误。

> Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Promise\Coroutine::of() in /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php:362 
> Stack trace: 
> #0 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(181): GuzzleHttp\Promise\coroutine() 
> #1 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php(79): GuzzleHttp\Command\ServiceClient->GuzzleHttp\Command\{closure}()
> #2 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}() 
> #3 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync() 
> #4 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute() 
> #5 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Qcloud/Cos/Client.php(223): GuzzleHttp\Command\ServiceClient->__call() 
> #6 /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Qcloud/Cos/Client.php(273): Qcloud\Cos\Client->__call() 
> #7 /usr/share/web/wp-content/plugins/sync-qcloud-cos/wordpress-qcloud-cos.php(156): Qcloud\Cos\Client->upload()
> #8 /usr/share/web/wp-content/plugins/sync-qcloud-cos/wordpress-qcloud-cos.php(294): cos_file_upload() 
> #9 /usr/share/web/wp-includes/class-wp-hook.php(309): cos_upload_thumbs() 
> #10 /usr/share/web/wp-includes/plugin.php(189): WP_Hook->apply_filters() 
> #11 /usr/share/web/wp-admin/includes/image.php(643): apply_filters() 
> #12 /usr/share/web/wp-admin/includes/media.php(421): wp_generate_attachment_metadata() 
> #13 /usr/share/web/wp-admin/async-upload.php(114): media_handle_upload() 
> #14 {main} thrown in /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/functions.php on line 362

**Comment by sy-records** [comment]
php8应该有问题，可以去这个目录下，执行composer update

/usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/

**Comment by AH-dark** [comment]
在运行 `composer update` 后我遇到了新的错误……

> Fatal error: Uncaught Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Utils.php:113 
> Stack trace: 
> 
> 1. /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent() 
> 2. /usr/share/web/wp-content/plugins/tencentcloud-cdn/includes/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent() 
> 3. /usr/share/web/wp-content/plugins/tencentcloud-cdn/includes/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults() 
> 4. /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Client.php(187): GuzzleHttp\Client->__construct() 
> 5. /usr/share/web/wp-content/plugins/sync-qcloud-cos/wordpress-qcloud-cos.php(99): Qcloud\Cos\Client->__construct() 
> 6. /usr/share/web/wp-content/plugins/sync-qcloud-cos/wordpress-qcloud-cos.php(580): cos_check_bucket() 
> 7. /usr/share/web/wp-includes/class-wp-hook.php(307): cos_setting_page() 
> 8. /usr/share/web/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() 
> 9. /usr/share/web/wp-includes/plugin.php(474): WP_Hook->do_action() 
> 10. /usr/share/web/wp-admin/admin.php(259): do_action() 
> 11. /usr/share/web/wp-admin/options-general.php(10): require_once('...') 
> 12. {main} thrown in /usr/share/web/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Utils.php on line 113

**Comment by AH-dark** [comment]
我觉得这可能是与腾讯云的官方插件 tencentcloud-cdn 冲突导致的，我会继续尝试

**Comment by AH-dark** [comment]
> 我觉得这可能是与腾讯云的官方插件 tencentcloud-cdn 冲突导致的，我会继续尝试

是的，在我删除这个插件以后，它正常了。

**Comment by sy-records** [comment]
嗯你不能同时启用两个插件，guzzle会冲突。

**Comment by AH-dark** [comment]
> 嗯你不能同时启用两个插件，guzzle会冲突。

谢谢大佬的解答，问题已经解决。不过还是建议将这类较易出现的问题写到一个较为明显的问题，以避免每个人都来提一遍Issue~
