### ISSUE TITLE
存储桶名称错误，可能是 XXX...

### ISSUE THREAD

**Issue by LeanderChen** [sy-records/wordpress-qcloud-cos#6]
**描述：**  
插件配置参数提交保存，失败错误提示“存储桶名称错误，可能是 XXX...”，经查桶名称无误且在提示列表中。
由于此时api secret使用的是子用户secret，权限限制了COS以外资源及API的访问出错，且查[参考说明](https://qq52o.me/2722.html)使用全局api secret，故更新全局secret后接入成功。
由于全局api secret使用具有极大的风险，建议作者更新新版本加入子用户访问支持。

**环境：**  
略。（未发现兼容性问题，如需另补）

**补充：**  
#3 
该Issue疑似同样情况。

**联络：**  
leander#tchost.cn

**Comment by sy-records** [comment]
appid需要填写为主账户的。
