### ISSUE TITLE
<?php前和?>后有空行，导致sitemap无法使用

### ISSUE THREAD

**Issue by steven52880** [sy-records/wordpress-qcloud-cos#7]
如题，删掉空行即可

**Comment by sy-records** [comment]
什么？sitemap和这个插件有什么关系呢？

**Comment by steven52880** [comment]
装了再装seo插件然后sitemap就报错打不开了

**Comment by sy-records** [comment]
什么插件？开启wp_debug有什么错误提示？

**Comment by steven52880** [comment]
Yoast SEO（其实根插件没关系）
是因为XML文件前面有空行导致错误。如果插件前面和后面有空行被include的时候就直接输出了嘛。
之前也试过同样的问题，去掉空行就好了。

**Comment by sy-records** [comment]
没遇到你说的问题，我插件哪里有空行？

**Comment by steven52880** [comment]
Wordpress“安装插件”里面安装的

**Comment by sy-records** [comment]
贴个图片看看

**Comment by steven52880** [comment]
https://web-1252733662.cos.ap-guangzhou.myqcloud.com/wordpress/批注-2020-03-11-143849.jpg
https://web-1252733662.cos.ap-guangzhou.myqcloud.com/wordpress/批注-2020-03-11-143943.jpg

**Comment by sy-records** [comment]
嗯知道了，可能是更新插件的时候多了一个符号，我重新发布下。
![image](https://user-images.githubusercontent.com/33931153/76389973-79a89100-63a7-11ea-96e8-5fd1c9d2149c.png)

**Comment by steven52880** [comment]
嗯

**Comment by sy-records** [comment]
升级下吧
